### ISSUE TITLE
how to run

### ISSUE THREAD

**Issue by taha183** [vida1338/exclusivo-sourcecode#1]
how to run??

**Comment by krecior** [comment]
> how to run??

i think node tokengenerator.js / in botting python main.py or smthng

**Comment by vida1338** [comment]
I don't even think this would work, python botter is broken because captcha bypass api is took down.
To run exclusivo v5, you need to remove licensing from window.js, remove their discord user checking system, and you would need something like `npm start`, i don't know tho, because i never run it, i just leaked the source code.
